repos:

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.4
    hooks:
      - id: ruff
        name: ruff
        files: ^(fractalsemantics|scripts)/

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.13.0
  #   hooks:
  #     - id: mypy
  #       name: mypy
  #       args: [--ignore-missing-imports, --no-strict-optional]
  #       files: ^fractalsemantics/
  #       additional_dependencies:
  #         - types-click
  #         - types-requests
